version: '2.0'
services:
  postgres:
    image: postgres
    restart: always
    container_name: mpit
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: mpit
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  postgres: